### ISSUE TITLE
About exam3  predict.py

### ISSUE THREAD

**Issue by Ray941216** [Ray941216/data-engineer-exam#2]
Is it possible that I get the anomaly points more than normal points? 
As the exam3 request, I aggregate the data from milliseconds to minutes data point.

<img width="330" alt="截圖 2020-06-17 下午1 54 32" src="https://user-images.githubusercontent.com/29003659/84860679-16af5000-b0a2-11ea-8fe2-e5d109852acb.png">

We get 386 minutes in training data. After predicting, I got 245 points anomaly points which is more than normal points. Is there any correct mapping for training data?

**Comment by cheyilin** [comment]
Hi @Ray941216,

Thanks for asking the question.

Could you please modify the issue and describe the question in English? This is also a test.
Thank you.

@nailo2c FYI.

**Comment by Ray941216** [comment]
@CheyiLin  I finally setup data-driven method. It can be tuned if anomaly specified.
I merged all answer into master branch. Please check the result. Thank you.

**Comment by cheyilin** [comment]
@nailo2c Please review this, thank you.

**Comment by aaron-y-chen** [comment]
@CheyiLin got it, I'll review ASAP, thanks!

**Comment by aaron-y-chen** [comment]
> Is it possible that I get the anomaly points more than normal points?

It's possible.

And your exam 3 solution I have already reviewed, I think it pretty nice. So you can close this issue, thank you!

**Comment by Ray941216** [comment]
Thank you for reviewing detaily. I think this is a very good exam for a data engineer candidates. It makes me recap the missing memory and it is also a good chance for me to merge the knowledge of both academic and industry. Thank you for these good exams.
