### ISSUE TITLE
exam 1: sensitive adjustment

### ISSUE THREAD

**Issue by nailo2c** [Ray941216/data-engineer-exam#3]
Hi @Ray941216 , your solution is gorgeous, nice work.

If our customers give feedback to us they are suffering from alert fatigue after applying your solution. How you improve your model or adjust the parameters to reduce the model alarm?

**Comment by Ray941216** [comment]
Thanks for question.  Intuitively, I will try below steps to reduce the model alarm.

-  Ask for more data. Model will learned more general pattern with giving more data.

-  I will try to change the alert mechanism for ignore too close anomaly.

- I will smooth the input data for models which means I will do more features explore and figure out what kind of features could be more accurate, more precision and lower recall.

**Comment by aaron-y-chen** [comment]
> Ask for more data. Model will learned more general pattern with giving more data.

Unfortunately, sometime we can't get more data.

> I will try to change the alert mechanism for ignore too close anomaly.

> I will smooth the input data for models which means I will do more features explore and figure out what kind of features could be more accurate, more precision and lower recall.

Could you try to implement these ideas?

**Comment by Ray941216** [comment]
> Could you try to implement these ideas?

Sure, it is being testing.

**Comment by Ray941216** [comment]
Hi @nailo2c please review again. I add some features for smoothing the data for models. Also fixed the always increasing data  for training. Thanks.

**Comment by aaron-y-chen** [comment]
Good, it looks like the issue of alert fatigue has been solved.
