### ISSUE TITLE
exam 1: model training time

### ISSUE THREAD

**Issue by nailo2c** [Ray941216/data-engineer-exam#4]
Hi @Ray941216 , I notice that `train_model` method uses the data in `self.data`. 

If this model runs on the service, the time of the `train_model` method would get longer and longer?

**Comment by Ray941216** [comment]
Yes, it would get longer and longer.  It will be fixed at next commit.

**Comment by aaron-y-chen** [comment]
Great, use `max_window` can fix the training size.
