### ISSUE TITLE
exam 2: improve the efficiency

### ISSUE THREAD

**Issue by nailo2c** [Ray941216/data-engineer-exam#5]
Hi @Ray941216 , great work for use `.groupby` method to aggregate the file.

However, it's very slow. If we transformer a huge size file, it will spend a long time.

Could you try to use other methods from `pandas` to improve efficiency?

**Comment by Ray941216** [comment]
Sure, I finished another attempts for this task.  Please review again.

However, I have different idea for this issue.

If the ```group by``` column  is been sorted, the performance I think is good at almost scenario.
In the ```lab-Copy1.ipynb``` shows the speed test is very close. 

Also, I will not use ```pandas```  to deal with too big data for grouping method, insted, I will use ```pyspark``` for the task.

**Comment by aaron-y-chen** [comment]
@Ray941216 the review is done, good job. Use `pyspark` is also a very good idea.
